// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdZYjHAStJfq_zeYJXLGf_9Xg9NbCawC4',
    appId: '1:822135113648:web:c3b24777c788405394b875',
    messagingSenderId: '822135113648',
    projectId: 'elderly-care-assistant',
    authDomain: 'elderly-care-assistant.firebaseapp.com',
    storageBucket: 'elderly-care-assistant.firebasestorage.app',
    measurementId: 'G-15SKWKLRJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXu9LHBMy7StE2JKyu6qZD1Wp64RC_fRU',
    appId: '1:822135113648:android:f0dfcbdc23b6a7f894b875',
    messagingSenderId: '822135113648',
    projectId: 'elderly-care-assistant',
    storageBucket: 'elderly-care-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5g3s1pAqUp_9gKnIFo23kw3-IZioU7Ac',
    appId: '1:822135113648:ios:c01fbad9af0a5b9e94b875',
    messagingSenderId: '822135113648',
    projectId: 'elderly-care-assistant',
    storageBucket: 'elderly-care-assistant.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCareApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5g3s1pAqUp_9gKnIFo23kw3-IZioU7Ac',
    appId: '1:822135113648:ios:c01fbad9af0a5b9e94b875',
    messagingSenderId: '822135113648',
    projectId: 'elderly-care-assistant',
    storageBucket: 'elderly-care-assistant.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCareApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdZYjHAStJfq_zeYJXLGf_9Xg9NbCawC4',
    appId: '1:822135113648:web:7a0fcfd3a758864b94b875',
    messagingSenderId: '822135113648',
    projectId: 'elderly-care-assistant',
    authDomain: 'elderly-care-assistant.firebaseapp.com',
    storageBucket: 'elderly-care-assistant.firebasestorage.app',
    measurementId: 'G-QG4PTVXSLH',
  );
}
